/**
 * STOCKLAB - Demo Financial Dataset & Synthetic Historical Generator
 * Provides realistic fundamental metrics, financial statements, analyst cases, and 250-bar OHLCV price series.
 */

// Helper to generate realistic historical OHLCV data with random walks and momentum
function generateHistoricalOHLCV(basePrice, volatility = 0.018, trend = 0.0004, count = 250) {
  const data = [];
  let currentClose = basePrice * 0.78; // Start 250 days ago at lower or base valuation
  const now = new Date();
  
  // Seedable deterministic-like variation
  for (let i = count; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i);
    // Skip weekends
    if (date.getDay() === 0 || date.getDay() === 6) continue;

    const changePercent = (Math.random() - 0.48) * volatility + trend;
    const open = currentClose * (1 + (Math.random() - 0.5) * 0.006);
    currentClose = open * (1 + changePercent);
    const high = Math.max(open, currentClose) * (1 + Math.random() * volatility * 0.8);
    const low = Math.min(open, currentClose) * (1 - Math.random() * volatility * 0.8);
    const volume = Math.floor(Math.random() * 25000000 + 15000000);

    data.push({
      date: date.toISOString().split('T')[0],
      open: parseFloat(open.toFixed(2)),
      high: parseFloat(high.toFixed(2)),
      low: parseFloat(low.toFixed(2)),
      close: parseFloat(currentClose.toFixed(2)),
      volume: volume
    });
  }

  // Ensure last close matches basePrice closely
  const lastIndex = data.length - 1;
  if (lastIndex >= 0) {
    data[lastIndex].close = basePrice;
    data[lastIndex].high = Math.max(data[lastIndex].high, basePrice);
    data[lastIndex].low = Math.min(data[lastIndex].low, basePrice);
  }

  return data;
}

const STOCK_DATABASE = {
  AAPL: {
    symbol: 'AAPL',
    companyName: 'Apple Inc.',
    exchange: 'NASDAQ',
    sector: 'Technology',
    industry: 'Consumer Electronics',
    currency: 'USD',
    price: 228.60,
    change: 3.45,
    changePercent: 1.53,
    marketCap: 3510000000000, // $3.51T
    marketCapFormatted: '$3.51T',
    pe: 34.2,
    forwardPe: 29.8,
    ps: 9.1,
    pb: 46.8,
    eps: 6.68,
    epsGrowth: 11.2,
    revenue: 385600000000,
    revenueFormatted: '$385.6B',
    revenueGrowth: 5.4,
    grossMargin: 46.2,
    operatingMargin: 30.7,
    netMargin: 25.8,
    roe: 147.2,
    roa: 28.5,
    debt: 104600000000,
    cash: 65200000000,
    debtToEquity: 1.45,
    freeCashFlow: 108000000000,
    fcfFormatted: '$108.0B',
    dividendYield: 0.44,
    payoutRatio: 15.2,
    beta: 1.08,
    fiftyTwoWeekHigh: 237.23,
    fiftyTwoWeekLow: 164.08,
    volume: 48200000,
    averageVolume: 52100000,
    description: 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories, and sells a variety of related services such as iCloud, App Store, and Apple Pay.',
    bullCase: 'Strong ecosystem lock-in, recurring services revenue expansion, and upcoming generative AI features on billions of active devices.',
    bearCase: 'Heavy reliance on iPhone hardware refresh cycles, lengthening smartphone replacement cycles, and regulatory antitrust scrutiny in the EU & US.',
    keyRisks: 'Supply chain concentration in Asia, geopolitical tensions, and potential App Store fee margin compression.',
    thesisInvalidation: 'Services revenue growth dropping below 5% YoY or sustained loss of premium smartphone market share.',
    historicalData: generateHistoricalOHLCV(228.60, 0.015, 0.0006)
  },

  MSFT: {
    symbol: 'MSFT',
    companyName: 'Microsoft Corporation',
    exchange: 'NASDAQ',
    sector: 'Technology',
    industry: 'Software - Infrastructure',
    currency: 'USD',
    price: 448.20,
    change: -2.15,
    changePercent: -0.48,
    marketCap: 3330000000000,
    marketCapFormatted: '$3.33T',
    pe: 36.8,
    forwardPe: 31.4,
    ps: 13.6,
    pb: 12.4,
    eps: 12.18,
    epsGrowth: 18.5,
    revenue: 245100000000,
    revenueFormatted: '$245.1B',
    revenueGrowth: 15.2,
    grossMargin: 69.8,
    operatingMargin: 44.6,
    netMargin: 35.8,
    roe: 38.6,
    roa: 19.2,
    debt: 79800000000,
    cash: 80200000000,
    debtToEquity: 0.35,
    freeCashFlow: 74100000000,
    fcfFormatted: '$74.1B',
    dividendYield: 0.67,
    payoutRatio: 24.8,
    beta: 0.92,
    fiftyTwoWeekHigh: 468.35,
    fiftyTwoWeekLow: 309.45,
    volume: 18400000,
    averageVolume: 21500000,
    description: 'Microsoft develops and supports software, services, devices and solutions. Key segments include Intelligent Cloud (Azure), Productivity & Business Processes (Office 365, LinkedIn), and More Personal Computing.',
    bullCase: 'Dominant enterprise cloud infrastructure leadership through Azure and early monetization of generative AI with Copilot.',
    bearCase: 'High capital expenditure (CapEx) in data centers putting short-term pressure on free cash flow margins.',
    keyRisks: 'Intense cloud competition with AWS and Google Cloud; potential AI adoption delays by conservative enterprise customers.',
    thesisInvalidation: 'Azure cloud growth decelerating significantly below 20% YoY.',
    historicalData: generateHistoricalOHLCV(448.20, 0.016, 0.0007)
  },

  NVDA: {
    symbol: 'NVDA',
    companyName: 'NVIDIA Corporation',
    exchange: 'NASDAQ',
    sector: 'Technology',
    industry: 'Semiconductors',
    currency: 'USD',
    price: 124.50,
    change: 4.80,
    changePercent: 4.01,
    marketCap: 3060000000000,
    marketCapFormatted: '$3.06T',
    pe: 68.5,
    forwardPe: 42.1,
    ps: 34.8,
    pb: 52.0,
    eps: 1.82,
    epsGrowth: 168.0,
    revenue: 96300000000,
    revenueFormatted: '$96.3B',
    revenueGrowth: 122.0,
    grossMargin: 75.3,
    operatingMargin: 62.1,
    netMargin: 55.4,
    roe: 115.6,
    roa: 64.2,
    debt: 11000000000,
    cash: 31400000000,
    debtToEquity: 0.19,
    freeCashFlow: 46800000000,
    fcfFormatted: '$46.8B',
    dividendYield: 0.03,
    payoutRatio: 2.1,
    beta: 1.68,
    fiftyTwoWeekHigh: 140.76,
    fiftyTwoWeekLow: 40.25,
    volume: 82000000,
    averageVolume: 94000000,
    description: 'NVIDIA pioneered GPU-accelerated computing. It provides AI supercomputing platforms, GPUs, CUDA software architecture, and networking hardware powering global cloud and enterprise AI clusters.',
    bullCase: 'Uncontested market share (>80%) in AI data center training and inference silicon, fortified by CUDA software moat.',
    bearCase: 'Extreme cyclicality risk if hyperscaler AI CapEx digests or slows down; custom chip competition from Big Tech.',
    keyRisks: 'TSMC semiconductor fabrication bottleneck and export restriction changes.',
    thesisInvalidation: 'Data center quarterly revenue sequentially declining or major loss of customer software lock-in.',
    historicalData: generateHistoricalOHLCV(124.50, 0.028, 0.0012)
  },

  TSLA: {
    symbol: 'TSLA',
    companyName: 'Tesla, Inc.',
    exchange: 'NASDAQ',
    sector: 'Consumer Cyclical',
    industry: 'Auto Manufacturers',
    currency: 'USD',
    price: 248.80,
    change: -5.60,
    changePercent: -2.20,
    marketCap: 792000000000,
    marketCapFormatted: '$792.0B',
    pe: 62.4,
    forwardPe: 54.0,
    ps: 8.2,
    pb: 11.5,
    eps: 3.98,
    epsGrowth: -24.0,
    revenue: 96800000000,
    revenueFormatted: '$96.8B',
    revenueGrowth: 3.2,
    grossMargin: 17.8,
    operatingMargin: 6.3,
    netMargin: 13.4,
    roe: 23.4,
    roa: 12.8,
    debt: 7800000000,
    cash: 30700000000,
    debtToEquity: 0.12,
    freeCashFlow: 3600000000,
    fcfFormatted: '$3.6B',
    dividendYield: 0.0,
    payoutRatio: 0.0,
    beta: 2.34,
    fiftyTwoWeekHigh: 271.00,
    fiftyTwoWeekLow: 138.80,
    volume: 68400000,
    averageVolume: 82000000,
    description: 'Tesla designs, develops, manufactures, and sells electric vehicles, energy generation and storage systems, and full self-driving (FSD) autonomous software.',
    bullCase: 'Long-term breakthrough in Full Self-Driving robotaxi fleets, energy storage exponential scaling, and humanoid robotics.',
    bearCase: 'Automotive gross margin compression driven by global price wars and intense Chinese EV competition.',
    keyRisks: 'Regulatory scrutiny on autonomous driving features; key person dependency.',
    thesisInvalidation: 'Energy storage growth stalling combined with continuous double-digit automotive margin decline.',
    historicalData: generateHistoricalOHLCV(248.80, 0.032, 0.0003)
  },

  AMZN: {
    symbol: 'AMZN',
    companyName: 'Amazon.com, Inc.',
    exchange: 'NASDAQ',
    sector: 'Consumer Cyclical',
    industry: 'Internet Retail',
    currency: 'USD',
    price: 186.40,
    change: 1.80,
    changePercent: 0.98,
    marketCap: 1940000000000,
    marketCapFormatted: '$1.94T',
    pe: 43.1,
    forwardPe: 32.5,
    ps: 3.2,
    pb: 8.4,
    eps: 4.32,
    epsGrowth: 110.0,
    revenue: 604300000000,
    revenueFormatted: '$604.3B',
    revenueGrowth: 12.5,
    grossMargin: 48.9,
    operatingMargin: 9.0,
    netMargin: 7.2,
    roe: 21.8,
    roa: 8.5,
    debt: 156000000000,
    cash: 89000000000,
    debtToEquity: 0.72,
    freeCashFlow: 51400000000,
    fcfFormatted: '$51.4B',
    dividendYield: 0.0,
    payoutRatio: 0.0,
    beta: 1.15,
    fiftyTwoWeekHigh: 201.20,
    fiftyTwoWeekLow: 118.35,
    volume: 34500000,
    averageVolume: 41200000,
    description: 'Amazon focuses on retail e-commerce, cloud computing (AWS), digital streaming, artificial intelligence, and high-margin digital advertising.',
    bullCase: 'Massive cash flow inflection from retail fulfillment efficiency and high-margin AWS cloud & advertising growth.',
    bearCase: 'Slowing retail e-commerce consumer spending and rising cloud price competition.',
    keyRisks: 'Antitrust regulation on third-party marketplace practices and high labor unionization pressures.',
    thesisInvalidation: 'Operating margin collapsing back below 4% or AWS market share loss.',
    historicalData: generateHistoricalOHLCV(186.40, 0.018, 0.0005)
  },

  GOOG: {
    symbol: 'GOOG',
    companyName: 'Alphabet Inc.',
    exchange: 'NASDAQ',
    sector: 'Communication Services',
    industry: 'Internet Content & Information',
    currency: 'USD',
    price: 178.50,
    change: 0.90,
    changePercent: 0.51,
    marketCap: 2210000000000,
    marketCapFormatted: '$2.21T',
    pe: 24.6,
    forwardPe: 20.8,
    ps: 6.8,
    pb: 6.9,
    eps: 7.25,
    epsGrowth: 31.0,
    revenue: 328200000000,
    revenueFormatted: '$328.2B',
    revenueGrowth: 14.0,
    grossMargin: 57.5,
    operatingMargin: 32.0,
    netMargin: 27.2,
    roe: 31.5,
    roa: 20.4,
    debt: 28400000000,
    cash: 110900000000,
    debtToEquity: 0.10,
    freeCashFlow: 69200000000,
    fcfFormatted: '$69.2B',
    dividendYield: 0.45,
    payoutRatio: 11.0,
    beta: 1.05,
    fiftyTwoWeekHigh: 191.75,
    fiftyTwoWeekLow: 120.21,
    volume: 21000000,
    averageVolume: 24800000,
    description: 'Alphabet is the parent holding company of Google, YouTube, Android, Google Cloud, and Other Bets (Waymo, Verily).',
    bullCase: 'Deepest full-stack AI research (Gemini, TPUs) integrated into Google Search, YouTube, and Google Cloud with fortress balance sheet.',
    bearCase: 'Search disruption risk from conversational AI interfaces and DOJ antitrust remedies.',
    keyRisks: 'Regulatory mandated restructuring of default browser search distribution agreements.',
    thesisInvalidation: 'Search ad revenue declining YoY or massive user defection to alternative search tools.',
    historicalData: generateHistoricalOHLCV(178.50, 0.016, 0.0005)
  },

  META: {
    symbol: 'META',
    companyName: 'Meta Platforms, Inc.',
    exchange: 'NASDAQ',
    sector: 'Communication Services',
    industry: 'Internet Content & Information',
    currency: 'USD',
    price: 512.40,
    change: 8.20,
    changePercent: 1.63,
    marketCap: 1300000000000,
    marketCapFormatted: '$1.30T',
    pe: 27.4,
    forwardPe: 22.8,
    ps: 8.7,
    pb: 8.1,
    eps: 18.70,
    epsGrowth: 73.0,
    revenue: 149700000000,
    revenueFormatted: '$149.7B',
    revenueGrowth: 22.1,
    grossMargin: 81.5,
    operatingMargin: 38.2,
    netMargin: 33.8,
    roe: 34.2,
    roa: 21.0,
    debt: 37100000000,
    cash: 58100000000,
    debtToEquity: 0.24,
    freeCashFlow: 48500000000,
    fcfFormatted: '$48.5B',
    dividendYield: 0.39,
    payoutRatio: 10.7,
    beta: 1.22,
    fiftyTwoWeekHigh: 542.80,
    fiftyTwoWeekLow: 279.40,
    volume: 14200000,
    averageVolume: 17500000,
    description: 'Meta Platforms builds technologies that help people connect. Products include Facebook, Instagram, WhatsApp, Messenger, Quest VR, and open-source Llama AI models.',
    bullCase: 'Supercharged digital advertising yield via AI recommendation algorithms (Reels, Advantage+) across 3.2B+ daily active people.',
    bearCase: 'Heavy losses in Reality Labs ($16B+ annualized) and potential teen social media regulations.',
    keyRisks: 'Ad platform signal loss from mobile operating system privacy changes.',
    thesisInvalidation: 'Family daily active people (DAP) turning negative across consecutive quarters.',
    historicalData: generateHistoricalOHLCV(512.40, 0.020, 0.0008)
  },

  AMD: {
    symbol: 'AMD',
    companyName: 'Advanced Micro Devices, Inc.',
    exchange: 'NASDAQ',
    sector: 'Technology',
    industry: 'Semiconductors',
    currency: 'USD',
    price: 148.30,
    change: 3.10,
    changePercent: 2.14,
    marketCap: 240000000000,
    marketCapFormatted: '$240.0B',
    pe: 112.0,
    forwardPe: 38.0,
    ps: 10.2,
    pb: 4.3,
    eps: 1.32,
    epsGrowth: 45.0,
    revenue: 23500000000,
    revenueFormatted: '$23.5B',
    revenueGrowth: 9.0,
    grossMargin: 52.1,
    operatingMargin: 8.5,
    netMargin: 7.2,
    roe: 3.8,
    roa: 3.1,
    debt: 3000000000,
    cash: 5300000000,
    debtToEquity: 0.05,
    freeCashFlow: 2100000000,
    fcfFormatted: '$2.1B',
    dividendYield: 0.0,
    payoutRatio: 0.0,
    beta: 1.72,
    fiftyTwoWeekHigh: 227.30,
    fiftyTwoWeekLow: 93.10,
    volume: 38000000,
    averageVolume: 46000000,
    description: 'AMD produces computer processors, server chips (EPYC), data center AI accelerators (MI300), and graphics cards for gaming and cloud workloads.',
    bullCase: 'Gaining market share from Intel in enterprise servers and emerging as the viable second-source AI chip provider.',
    bearCase: 'Lags behind NVIDIA in developer software ecosystem maturity (ROCm vs CUDA).',
    keyRisks: 'PC and gaming cyclical downturns.',
    thesisInvalidation: 'MI300 series AI GPU sales missing revenue forecasts significantly.',
    historicalData: generateHistoricalOHLCV(148.30, 0.026, 0.0004)
  },

  NFLX: {
    symbol: 'NFLX',
    companyName: 'Netflix, Inc.',
    exchange: 'NASDAQ',
    sector: 'Communication Services',
    industry: 'Entertainment',
    currency: 'USD',
    price: 685.20,
    change: 5.40,
    changePercent: 0.79,
    marketCap: 294000000000,
    marketCapFormatted: '$294.0B',
    pe: 42.0,
    forwardPe: 32.8,
    ps: 8.1,
    pb: 13.5,
    eps: 16.30,
    epsGrowth: 48.0,
    revenue: 36300000000,
    revenueFormatted: '$36.3B',
    revenueGrowth: 16.8,
    grossMargin: 44.0,
    operatingMargin: 27.2,
    netMargin: 20.1,
    roe: 36.4,
    roa: 14.8,
    debt: 14200000000,
    cash: 7200000000,
    debtToEquity: 0.68,
    freeCashFlow: 6800000000,
    fcfFormatted: '$6.8B',
    dividendYield: 0.0,
    payoutRatio: 0.0,
    beta: 1.25,
    fiftyTwoWeekHigh: 711.33,
    fiftyTwoWeekLow: 344.73,
    volume: 2900000,
    averageVolume: 3400000,
    description: 'Netflix is one of the world\'s leading entertainment streaming services with over 277 million paid memberships in over 190 countries.',
    bullCase: 'Undisputed global streaming profitability, ad-tier subscriber scaling, and paid-sharing monetization success.',
    bearCase: 'High content spend inflation and rising domestic saturation.',
    keyRisks: 'Foreign exchange headwinds and consumer subscription fatigue.',
    thesisInvalidation: 'Global net subscriber additions stalling or free cash flow declining.',
    historicalData: generateHistoricalOHLCV(685.20, 0.018, 0.0007)
  },

  AVGO: {
    symbol: 'AVGO',
    companyName: 'Broadcom Inc.',
    exchange: 'NASDAQ',
    sector: 'Technology',
    industry: 'Semiconductors',
    currency: 'USD',
    price: 156.70,
    change: 2.80,
    changePercent: 1.82,
    marketCap: 730000000000,
    marketCapFormatted: '$730.0B',
    pe: 58.2,
    forwardPe: 28.5,
    ps: 15.2,
    pb: 10.4,
    eps: 2.69,
    epsGrowth: 28.0,
    revenue: 47000000000,
    revenueFormatted: '$47.0B',
    revenueGrowth: 43.0,
    grossMargin: 64.5,
    operatingMargin: 38.0,
    netMargin: 26.5,
    roe: 19.8,
    roa: 9.8,
    debt: 71000000000,
    cash: 10500000000,
    debtToEquity: 1.05,
    freeCashFlow: 19500000000,
    fcfFormatted: '$19.5B',
    dividendYield: 1.35,
    payoutRatio: 52.0,
    beta: 1.18,
    fiftyTwoWeekHigh: 185.16,
    fiftyTwoWeekLow: 79.50,
    volume: 16800000,
    averageVolume: 22000000,
    description: 'Broadcom is a global technology leader designing custom AI ASICs (XPU for hyperscalers), enterprise networking switches (Tomahawk), and VMware enterprise virtualization software.',
    bullCase: 'Essential custom AI silicon partner for Alphabet and Meta, combined with massive VMware recurring software cash flows.',
    bearCase: 'High debt burden post-VMware acquisition requiring disciplined deleveraging.',
    keyRisks: 'Customer concentration in top 2 custom ASIC clients.',
    thesisInvalidation: 'Loss of primary custom ASIC co-design contract with major hyperscaler.',
    historicalData: generateHistoricalOHLCV(156.70, 0.020, 0.0008)
  },

  // Indian Equities (NSE / BSE)
  RELIANCE: {
    symbol: 'RELIANCE',
    companyName: 'Reliance Industries Ltd.',
    exchange: 'NSE',
    sector: 'Energy & Conglomerate',
    industry: 'Oil, Gas & Retail/Telecom',
    currency: 'INR',
    price: 2980.50,
    change: 22.40,
    changePercent: 0.76,
    marketCap: 20160000000000, // ₹20.16 Lakh Cr
    marketCapFormatted: '₹20.16T',
    pe: 28.4,
    forwardPe: 24.2,
    ps: 2.1,
    pb: 2.6,
    eps: 105.0,
    epsGrowth: 12.0,
    revenue: 9740000000000,
    revenueFormatted: '₹9.74T',
    revenueGrowth: 10.5,
    grossMargin: 24.0,
    operatingMargin: 17.5,
    netMargin: 8.2,
    roe: 9.8,
    roa: 5.2,
    debt: 3100000000000,
    cash: 1800000000000,
    debtToEquity: 0.42,
    freeCashFlow: 850000000000,
    fcfFormatted: '₹850B',
    dividendYield: 0.35,
    payoutRatio: 9.5,
    beta: 0.88,
    fiftyTwoWeekHigh: 3217.90,
    fiftyTwoWeekLow: 2220.30,
    volume: 6400000,
    averageVolume: 7800000,
    description: 'Reliance Industries is India\'s largest private sector corporation, operating energy refining and petrochemicals, Jio digital connectivity, and Reliance Retail.',
    bullCase: 'Transformation from legacy oil refining to digital telecom and retail dominance, plus multi-billion green energy gigafactories.',
    bearCase: 'Refining margin volatility and high capital expenditure cycle in 5G and retail infrastructure.',
    keyRisks: 'Global crude crack spread swings and regulatory tariff revisions.',
    thesisInvalidation: 'Jio ARPU growth stagnating below inflation.',
    historicalData: generateHistoricalOHLCV(2980.50, 0.014, 0.0005)
  },

  TCS: {
    symbol: 'TCS',
    companyName: 'Tata Consultancy Services Ltd.',
    exchange: 'NSE',
    sector: 'Technology',
    industry: 'IT Services & Consulting',
    currency: 'INR',
    price: 4320.00,
    change: 35.80,
    changePercent: 0.84,
    marketCap: 15600000000000,
    marketCapFormatted: '₹15.60T',
    pe: 32.1,
    forwardPe: 28.0,
    ps: 6.2,
    pb: 14.8,
    eps: 134.50,
    epsGrowth: 10.4,
    revenue: 2450000000000,
    revenueFormatted: '₹2.45T',
    revenueGrowth: 7.2,
    grossMargin: 42.0,
    operatingMargin: 25.8,
    netMargin: 19.8,
    roe: 48.0,
    roa: 31.0,
    debt: 85000000000,
    cash: 480000000000,
    debtToEquity: 0.08,
    freeCashFlow: 440000000000,
    fcfFormatted: '₹440B',
    dividendYield: 1.45,
    payoutRatio: 72.0,
    beta: 0.72,
    fiftyTwoWeekHigh: 4585.90,
    fiftyTwoWeekLow: 3313.00,
    volume: 2100000,
    averageVolume: 2500000,
    description: 'TCS is India\'s premier multinational IT services, consulting, and business solutions organization, serving global Fortune 500 enterprises.',
    bullCase: 'Unmatched scale, rock-solid operating margins (>25%), industry-leading ROE, and strong deal pipeline in enterprise AI transformations.',
    bearCase: 'Cautious global enterprise discretionary IT spending and delayed project ramp-ups.',
    keyRisks: 'US and European macroeconomic slowdown; H-1B visa policy changes.',
    thesisInvalidation: 'Operating margin falling below 22% or net employee attrition spiking.',
    historicalData: generateHistoricalOHLCV(4320.00, 0.012, 0.0004)
  },

  INFY: {
    symbol: 'INFY',
    companyName: 'Infosys Limited',
    exchange: 'NSE',
    sector: 'Technology',
    industry: 'IT Services & Consulting',
    currency: 'INR',
    price: 1845.20,
    change: -12.10,
    changePercent: -0.65,
    marketCap: 7650000000000,
    marketCapFormatted: '₹7.65T',
    pe: 29.2,
    forwardPe: 25.4,
    ps: 4.8,
    pb: 8.9,
    eps: 63.20,
    epsGrowth: 8.5,
    revenue: 1580000000000,
    revenueFormatted: '₹1.58T',
    revenueGrowth: 6.0,
    grossMargin: 38.5,
    operatingMargin: 21.4,
    netMargin: 17.2,
    roe: 32.5,
    roa: 21.0,
    debt: 78000000000,
    cash: 185000000000,
    debtToEquity: 0.10,
    freeCashFlow: 235000000000,
    fcfFormatted: '₹235B',
    dividendYield: 2.10,
    payoutRatio: 68.0,
    beta: 0.85,
    fiftyTwoWeekHigh: 1953.90,
    fiftyTwoWeekLow: 1358.35,
    volume: 5200000,
    averageVolume: 6100000,
    description: 'Infosys is a global leader in next-generation digital services and consulting, enabling clients across 56 countries to navigate digital transformation with Topaz AI suite.',
    bullCase: 'Large deal total contract value (TCV) momentum and attractive dividend yield for tech investors.',
    bearCase: 'High wage inflation in senior engineering talent and slower banking sector IT renewals.',
    keyRisks: 'North American banking and telecom discretionary project cancellations.',
    thesisInvalidation: 'Consecutive downward revisions in annual constant-currency revenue guidance.',
    historicalData: generateHistoricalOHLCV(1845.20, 0.015, 0.0004)
  },

  HDFCBANK: {
    symbol: 'HDFCBANK',
    companyName: 'HDFC Bank Limited',
    exchange: 'NSE',
    sector: 'Financial Services',
    industry: 'Private Banks',
    currency: 'INR',
    price: 1650.40,
    change: 14.20,
    changePercent: 0.87,
    marketCap: 12550000000000,
    marketCapFormatted: '₹12.55T',
    pe: 18.9,
    forwardPe: 16.2,
    ps: 4.2,
    pb: 2.7,
    eps: 87.30,
    epsGrowth: 18.2,
    revenue: 2980000000000,
    revenueFormatted: '₹2.98T',
    revenueGrowth: 26.0,
    grossMargin: 72.0,
    operatingMargin: 36.5,
    netMargin: 21.8,
    roe: 16.5,
    roa: 1.95,
    debt: 22000000000000,
    cash: 2500000000000,
    debtToEquity: 6.8,
    freeCashFlow: 380000000000,
    fcfFormatted: '₹380B',
    dividendYield: 1.20,
    payoutRatio: 22.0,
    beta: 0.95,
    fiftyTwoWeekHigh: 1794.00,
    fiftyTwoWeekLow: 1363.55,
    volume: 14200000,
    averageVolume: 16500000,
    description: 'HDFC Bank is India\'s largest private sector lender by assets, offering retail banking, wholesale banking, treasury, and mortgage financing.',
    bullCase: 'Long-term merger synergies with parent HDFC Ltd, massive branch network expansion, and pristine loan underwriting quality.',
    bearCase: 'Elevated Credit-to-Deposit (CD) ratio post-merger requiring aggressive deposit mobilization.',
    keyRisks: 'Net Interest Margin (NIM) compression in high interest rate cycles.',
    thesisInvalidation: 'Gross Non-Performing Assets (GNPA) climbing above 2.0%.',
    historicalData: generateHistoricalOHLCV(1650.40, 0.013, 0.0003)
  },

  ICICIBANK: {
    symbol: 'ICICIBANK',
    companyName: 'ICICI Bank Limited',
    exchange: 'NSE',
    sector: 'Financial Services',
    industry: 'Private Banks',
    currency: 'INR',
    price: 1230.80,
    change: 9.60,
    changePercent: 0.79,
    marketCap: 8650000000000,
    marketCapFormatted: '₹8.65T',
    pe: 18.2,
    forwardPe: 15.5,
    ps: 4.0,
    pb: 3.1,
    eps: 67.60,
    epsGrowth: 24.0,
    revenue: 2150000000000,
    revenueFormatted: '₹2.15T',
    revenueGrowth: 21.5,
    grossMargin: 68.0,
    operatingMargin: 35.0,
    netMargin: 23.4,
    roe: 18.8,
    roa: 2.35,
    debt: 16000000000000,
    cash: 1900000000000,
    debtToEquity: 5.9,
    freeCashFlow: 310000000000,
    fcfFormatted: '₹310B',
    dividendYield: 0.85,
    payoutRatio: 16.0,
    beta: 1.02,
    fiftyTwoWeekHigh: 1257.80,
    fiftyTwoWeekLow: 918.00,
    volume: 11000000,
    averageVolume: 12800000,
    description: 'ICICI Bank is a premier Indian private sector bank offering diverse financial products and services to retail and corporate customers through iMobile Pay.',
    bullCase: 'Best-in-class Return on Assets (>2.3%), robust core operating profit growth, and superior digital execution.',
    bearCase: 'Growth moderation as the high credit cycle matures in unsecured retail portfolios.',
    keyRisks: 'Unsecured personal loan and credit card delinquency uptick.',
    thesisInvalidation: 'Return on Equity dropping below 14%.',
    historicalData: generateHistoricalOHLCV(1230.80, 0.014, 0.0005)
  }
};

// Major Market Indices
const MARKET_INDICES = [
  { symbol: '^GSPC', name: 'S&P 500', value: '5,567.19', change: '+32.48', changePercent: '+0.59%', isUp: true },
  { symbol: '^IXIC', name: 'NASDAQ', value: '17,879.30', change: '+182.20', changePercent: '+1.03%', isUp: true },
  { symbol: '^DJI', name: 'DOW JONES', value: '40,843.82', change: '-65.11', changePercent: '-0.16%', isUp: false },
  { symbol: '^RUT', name: 'RUSSELL 2000', value: '2,217.50', change: '+14.90', changePercent: '+0.68%', isUp: true },
  { symbol: '^NSEI', name: 'NIFTY 50', value: '25,279.85', change: '+92.80', changePercent: '+0.37%', isUp: true }
];

// Market Sectors
const MARKET_SECTORS = [
  { name: 'Technology', performance: '+1.42%', isUp: true, leadingStock: 'NVDA' },
  { name: 'Communication Services', performance: '+0.95%', isUp: true, leadingStock: 'META' },
  { name: 'Financial Services', performance: '+0.58%', isUp: true, leadingStock: 'ICICIBANK' },
  { name: 'Consumer Cyclical', performance: '+0.32%', isUp: true, leadingStock: 'AMZN' },
  { name: 'Industrials', performance: '-0.18%', isUp: false, leadingStock: 'CAT' },
  { name: 'Energy', performance: '-0.64%', isUp: false, leadingStock: 'XOM' },
  { name: 'Healthcare', performance: '-0.45%', isUp: false, leadingStock: 'UNH' }
];

// Market Movers
const MARKET_MOVERS = {
  gainers: [
    { symbol: 'NVDA', name: 'NVIDIA Corp.', price: '$124.50', change: '+4.01%' },
    { symbol: 'AMD', name: 'Advanced Micro Devices', price: '$148.30', change: '+2.14%' },
    { symbol: 'AVGO', name: 'Broadcom Inc.', price: '$156.70', change: '+1.82%' },
    { symbol: 'META', name: 'Meta Platforms', price: '$512.40', change: '+1.63%' },
    { symbol: 'AAPL', name: 'Apple Inc.', price: '$228.60', change: '+1.53%' }
  ],
  losers: [
    { symbol: 'TSLA', name: 'Tesla, Inc.', price: '$248.80', change: '-2.20%' },
    { symbol: 'INFY', name: 'Infosys Ltd.', price: '₹1,845.20', change: '-0.65%' },
    { symbol: 'MSFT', name: 'Microsoft Corp.', price: '$448.20', change: '-0.48%' }
  ],
  active: [
    { symbol: 'NVDA', name: 'NVIDIA Corp.', volume: '82.0M', price: '$124.50' },
    { symbol: 'TSLA', name: 'Tesla, Inc.', volume: '68.4M', price: '$248.80' },
    { symbol: 'AAPL', name: 'Apple Inc.', volume: '48.2M', price: '$228.60' },
    { symbol: 'AMD', name: 'Advanced Micro Devices', volume: '38.0M', price: '$148.30' }
  ]
};

// Categorized Financial News
const FINANCIAL_NEWS = [
  {
    id: 1,
    headline: 'Semiconductor Demand Surges as Next-Generation Enterprise AI Deployments Accelerate',
    source: 'Financial Times Demo',
    time: '25m ago',
    ticker: 'NVDA',
    category: 'Technology',
    summary: 'Data center spending remains robust as cloud hyperscalers order custom silicon and next-generation GPU racks.'
  },
  {
    id: 2,
    headline: 'Apple Unveils System Architecture for Private Cloud Compute AI Infrastructure',
    source: 'Bloomberg Demo',
    time: '1h ago',
    ticker: 'AAPL',
    category: 'Company',
    summary: 'The new on-device and private cloud verification model aims to protect sensitive user telemetry during generative inference.'
  },
  {
    id: 3,
    headline: 'Global Central Banks Signal Measured Approach to Interest Rate Normalization',
    source: 'Reuters Demo',
    time: '3h ago',
    ticker: 'MARKETS',
    category: 'Economy',
    summary: 'Policymakers balance resilient labor markets against softening headline inflation in major developed economies.'
  },
  {
    id: 4,
    headline: 'Indian IT Giants Report Resilient Large Deal Pipeline Despite Global Macro Headwinds',
    source: 'Mint Demo',
    time: '4h ago',
    ticker: 'TCS',
    category: 'Earnings',
    summary: 'Transformation deals in digital modernization and generative AI integration offset slower discretionary spending.'
  },
  {
    id: 5,
    headline: 'Cloud Hyperscalers Reiterate Aggressive Infrastructure CapEx Commitments',
    source: 'Wall St Journal Demo',
    time: '6h ago',
    ticker: 'MSFT',
    category: 'Technology',
    summary: 'Long-term enterprise contracts indicate growing workload migration toward hybrid AI cloud ecosystems.'
  }
];

// Upcoming Earnings Calendar
const UPCOMING_EARNINGS = [
  { symbol: 'AAPL', company: 'Apple Inc.', date: 'Oct 31, 2024 (AMC)', expectedEps: '$1.58', expectedRev: '$94.2B' },
  { symbol: 'MSFT', company: 'Microsoft Corp.', date: 'Oct 29, 2024 (AMC)', expectedEps: '$3.10', expectedRev: '$64.5B' },
  { symbol: 'GOOG', company: 'Alphabet Inc.', date: 'Oct 29, 2024 (AMC)', expectedEps: '$1.84', expectedRev: '$86.3B' },
  { symbol: 'AMZN', company: 'Amazon.com', date: 'Oct 31, 2024 (AMC)', expectedEps: '$1.14', expectedRev: '$157.2B' },
  { symbol: 'NVDA', company: 'NVIDIA Corp.', date: 'Nov 20, 2024 (AMC)', expectedEps: '$0.74', expectedRev: '$32.8B' },
  { symbol: 'TCS', company: 'Tata Consultancy', date: 'Oct 10, 2024', expectedEps: '₹34.50', expectedRev: '₹642B' },
  { symbol: 'RELIANCE', company: 'Reliance Industries', date: 'Oct 18, 2024', expectedEps: '₹28.20', expectedRev: '₹2.45T' }
];
